### ISSUE TITLE
Implement time schema for History3G where possible

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#2793]
Issue for task for History3G, basic time schema, needs to parsed and some actions taken
```
time_spec:
  six_hourly: &six_hourly​
    mode: instantaneous​
    frequency: <ISO duration>  # e.g., P6H​
    ref_time: <ISO time>       # e.g., T21H (no date)​
    start: <ISO time>  # e.g., 2020-01-01​
    end:   <ISO time>  # default is end of universe
```
Each collection will reference a time spec. For now the mode is irrelevant until @tclune or someone else implements the ability of the coupling layer to time-average and a way to tell the coupling to do this.

The other items are straightforward:

Given the frequency and ref_time (if no ref time default to 0z) create an alarm we can use to decide when to write in the run method. The alarm should be stored in the collection components private state.

The other two the start and end are simply a time that if you are before or after the time don't write anything.
The default for start is simply when the application initialized, i.e. whatever the initial time of the clock is. The end default it the end of the universe or the closest representable thing in an ESMF time.
Likewise this information will have to go in the collection components private state.
