### ISSUE TITLE
Should ExtData have an option to set an offset of the clock DT rather than ISO duration

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3000]
When trying to trace problem in GAAS (which we eventually traced to the fact that no one ever updated the files in the AMIP directory there for GAAS to correctly function) I remembered I have to set an offset in the ExtData file for GAAS that is the model heartbeat like so as in this example:
```
Collections:
  aod_a.sfc.%y4%m2%d2_%h2%n2z.nc4:
   template: das.aod_a.sfc.%y4%m2%d2_%h2%n2z.nc4
   freq: PT3H

Samplings:
  GAAS_sample_0:
   update_offset: PT450S
   exact: True

Exports:
  aod_a:
    collection: aod_a.sfc.%y4%m2%d2_%h2%n2z.nc4
    sample: GAAS_sample_0
    variable: AOD
    fail_on_missing_file: false
```
The reason for this is that GAAS runs 1 heartbeat before the start of the hour. So if you start at 21z, GAAS runs 1 heartbeat before 0z, 3z, 6z, etc. But the files GAAS needs are timestamped on the hours, so essentially GAAS needs the file timestamped 1 heartbeat in the future.
Notice that I have to set an offset, and that offset needs to be the heartbeat of the clock and apparently when this file was made it was for a 7.5 minute heartbeat. So this is an accident waiting to happen, if the user changes the heartbeat in CAP.rc, this needs to change too.

I'm thinking we have some notion of a HEARTBEAT you specify for that offset frequency. So rather than an ISO duration you could alternatively specify a number of hearbeats of the clock. That fixes this accident waiting to happen.
