### ISSUE TITLE
Specify short name of vertical grid coordinate in yaml file, instead of hardwiring them in parse_geometry_spec

### ISSUE THREAD

**Issue by pchakraborty** [GEOS-ESM/MAPL#3184]
These cannot be hardwired here.  At least not in the long term.   How about requiring them in the yaml file when you try to specify the vertical grid that way:
```yaml
vertical_grid:
    coordinate:
        dimension: pressure
        stagger: edge
        field: PLE
    coordinate:
        dimension: height
        stagger: center
        field: ZL
...
```

_Originally posted by @tclune in https://github.com/GEOS-ESM/MAPL/pull/3182#discussion_r1843919531_
