### ISSUE TITLE
Refactor/reengineer ExtDataGridComp

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#345]
Some requirements I have
* Format for config will be redone from scratch
  * Allow for optional or default arguments. Current space separated format does not allow for this at all and must go.
  * Should be YAML and not something like the CSV used by old auto-code generator.
* Prefetching to actually make use of the asynchronous IO ability of server.
* Refactor code, beyond the config the handling of the logic to find the correct file to read has gotten so convoluted it is almost impossible to follow and would be my next priority.
* Probably want fine grain unit testing, is what I have too high level?

**Comment by bena-nasa** [comment]
Current situation with the config file:
The ExtData currently consists of single line, space separated entries in  Primary entry blocks plus the ability to have what Arlindo and Anton first termed "derived entries"
```
PrimaryExports%%
IMPORT_NAME 'kg C m-2 s-1'      N Y 0 none     none     file_var_name file_template <optional file reference time and frequency>
%%
```
In some sense this is like a dictionary in that the first entry is a key but the parsing of this just a pain in the ass now with ESMF config. The rest of the entries have specific fixed meanings.

What is wrong with this now. 
1. This is inextensible with new options, there is all ready an optional entry after the file template, but I can't add any new ones as the need arises or restructure the existing ones to make logical sense.
2. Some of these aren't even used, the units were added at the start when Anton/Arlindo coded this but we never use them so why does every have them.
3. A lot of these could just have defaults and no need to even have an entry unless you want to override, for example, the scaling/shifting, most of the time that is not used. But going back to 1, there is no flexibility for you can put so even if 99% of the entries take the same no-opt value it has to be there.
4. Because of 1 and 3 too much functionality was added to the existing entries. For example, there was in the beginning the refresh template that controls when the pointer is updated, i.e. every timestep or some other interval, but whenever it is updated it time interpolates to the current time. Then someone asked for the ability to interpolate to a shifted time, then someone asked for the ability to not time interpolate at all, just fix the value until the next time in the files, so now 0, F0, and 0;3000 are valid entries, among others, because there is no format that allows for clear and new keywords to expand functionality as needed.

**Comment by bena-nasa** [comment]
Each entry could be single yaml key/dictionary like so with the keywords I decide are needed for a clearer expression of provided capabilities.
```
T:
   file_var: T
   file_template: file_path
   regrid_method: bilinear
   scaling: none
   shift: none
   refresh_frequency: 0
   time_interpolation: True
   allow_extrapolation: False
BIOMASS:
   file_var: biomass
   file_template: file_path
   regrid_method: conservative
   scaling: none
   shift: none
   refresh_frequency: 0
   time_interpolation: True
   allow_extrapolation: False
   ```

this could get quite long and verbose, but in reality many entries could still be on a single line because most people will be using the defaults
T: {file_var: T, file_template: file_path}
BIOMASS: {file_var: biomass, file_template: file_path}

What about some other grouping?
Group by file template if you have a bunch of entries using a common file template. 
To me this seams unnatural because I'm getting a list of names coming into ExtData so these seem like the most natural "keys"
If yaml parser supported anchors for example that would be a way to avoid repeatedly typing log file paths.

**Comment by bena-nasa** [comment]
Note for myself, the keys I would use for each entry:
file_var (variable name on the file)
file_template (file template)
file_reference_time (file reference time, needed if file frequency can't be guessed from template)
file_frequency (file frequency, needed if the file frequency can't be guessed from template)
regrid_method (obvious)
climatology (treat dataset a climatology, some thought needed this could be a logical or a year)
allow_extrapolation (currently a global option added by harvard, should really be on per entry basis)
scaling (obvious)
shifting (obvious)
time_interpolation (time interpolate or persist)
refresh_frequency (frequency of pointer update)
refresh_reference_date (reference date for pointer update if applicable)
time_offset (offset time used for time interpolation)
vector_partner (do I have a vector pair)
vector_component (which component am I)

**Comment by lizziel** [comment]
For climatology, there is also option D for day-of-week scale factors used in GCHP. So logical or year won't quite work unless we add another key for that option.

**Comment by mathomp4** [comment]
One thing we could do, though probably not necessary right now, is keep/add things like `units`, `standard_name`, `long_name`, etc., the "basic" bits used for CF compliance.

I guess `standard_name` should eventually be what the template is based on, but I just have this feeling in the back of my head that Arlindo, or someone, will want `units` back...

**Comment by tclune** [comment]
In theory we will be obtaining units from the NUOPC field dictionary.   They are looked up with the standard name.

**Comment by tclune** [comment]
> 
> What about some other grouping?
> Group by file template if you have a bunch of entries using a common file template and other common parameters, ala History?
> To me this seams unnatural because I'm getting a list of names from the incoming fields into ExtData so these seem like the most natural "keys"
> If yaml parser supported anchors for example that would be a way to avoid repeatedly typing long file paths.

Maybe two sections.  The first is a set of templates with the appropriate key-value pairs for that template.   The second is a list of variables that specifies which template they use?

**Comment by tclune** [comment]
@mathomp4 if the file contains units, then my expectation would be that the system would do unit conversions if the units did not agree with what the model provides.   Or at the very least that it would fail if the units don't agree.   Is that the current behavior?

**Comment by lizziel** [comment]
From a GCHP-perspective, I support excluding the units. HEMCO has automatic unit conversions and it has been a continual source of confusion to users. Do the units reflect what is coming in or what the target is? If units are to be included then it needs to be very clear what they mean and what the resulting behavior will be. If they are simply the units in the file then it seems redundant and extra work for proper configuration.

**Comment by bena-nasa** [comment]
> @mathomp4 if the file contains units, then my expectation would be that the system would do unit conversions if the units did not agree with what the model provides. Or at the very least that it would fail if the units don't agree. Is that the current behavior?

Right now there is no checking of the units between the field and the file.

**Comment by bena-nasa** [comment]
Seb, Lizzie, good discussion today.
I think the biggest thing I got out of it is that if we do the extrapolation right and have the notion a user specified valid range for the file it greatly simplifies the extrapolation algorithm and makes the need for a separate notion of a climatology redundant.

This is what I am thinking for the input format that captures the existing functionality, we can expand from this once I take a look at what you do in HEMCO for the extra extrapolation options.  In addition we do have this notion of a derived entry in the existing structure. One possibility is those could be handled as any other rule, but the key difference is they do not point to a dataset but have the expression used to evaluate the field instead.

First we have a data_set section where the file streams are specified. Then we have the rules for the fields that reference a particular data_set entry
A few things to note. 
 - Tom suggested keeping the U;V notation for vectors. I can split these up as two entries when I parse the file.
- For specifying any time interval or time I want to try to stick to the ISO time format: https://en.wikipedia.org/wiki/ISO_8601
For the data_sets, I can think of these 3 keywords:
file_reference_time: 
file_frequency:
valid_years:
The first two are needed for describing the file structure on disk in the case it is not obvious from the template (i.e. files with a minute token in the template) that is currently contained in the one optional entry in the current RC file format.
The valid_years or some other name would encompass what we talked about today for specify a file range to assist with extrapolation as well as eliminate the climatology.

For the rules
      file_var: file on disk (no default *)
      file_template_key: key for dataset (no default *)
      allow_extrapolation: whether to allow extrapolation outside of specified range in dataset (default ?)
      regrid_method: regridding method (default bilinear)
      refresh_reference_date: a reference date used in conjunction with the refresh frequency (default application start date)
      refresh_frequency: frequency to update the pointer from reference date (default update every time)
      time_offset: offset to time used when computing target time (default no offset)
      time_interpolation: either linear between brackets or piece constant from left (default linear)
      scaling: scale factor for field (default none)
      shift: shift applied to field (default none)
     * expression: expression used to evaluate field instead of a data set (derived entry in old parlance, needs thought)

As an example
```
data_sets:
   fstream1: {file_template: path1}
   fstream2: {file_template: path2, file_reference_time: "2000-04-14T21:00", file_frequency: PT3H}
   qfed_v2.5: {file_tempalte: path3, valid_years: "2000-2005"}
   arctas:  {file_tempalte: path4}

rules:
   T: {file_var: T, file_template_key: fstream1}
   Q: {file_var: QV, file_template_key: fstream2, interpolation_method: linear}
   U;V:
      file_var: U;V
      file_template_key: fstream2
      allow_extrapolation: False
      regrid_method: REGRID_METHOD_CONSERVATIVE
      refresh_reference_date: "1990-01-01Y00:00"
      refresh_frequency: P1D
      time_offset: PT12H
      time_interpolation: piecewise
      scaling: 2.0
      shift: 1.0
   CO_RegionMask: {file_var: REGION_MASK, file_template_key: arctas, regrid_method: REGRID_METHOD_VOTING, refresh_frequency "once" }
   CO_BIOMASS: {file_var: biomass, file_template_key: qved_v2.5}
   CO_BIOMASSbbae: { expression: regionmask(CO_BIOMASS,CO_regionMask;3,9,10) }
```
