### ISSUE TITLE
Yaml ACG example

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#3735]
@tclune Just for comparisons sake and fun since I brought it up again, to see what they would look like side by side and an example of where I think the excel like format fall flat.

Current:
```
component: DU
category: IMPORT
#----------------------------------------------------------------------------------------
#  VARIABLE                | DIMENSIONS  |          Additional Metadata
#----------------------------------------------------------------------------------------
     NAME     | UNITS      | DIMS | VLOC | UNGRIDDED | RESTART | LONG NAME
#----------------------------------------------------------------------------------------
 LWI          | 1          | xy   | N    |           | OPT     | land-ocean-ice_mask
 TROPP        | Pa         | xy   | N    |           | OPT     | tropopause_pressure_based_on_blended_estimate
 USTAR        | m s-1      | xy   | N    |           | OPT     | surface_velocity_scale
 ZPBL         | m          | xy   | N    |           | OPT     | planetary_boundary_layer_height
 SH           | w m-2      | xy   | N    |           | OPT     | sensible_heat_flux_from_turbulence
 Z0H          | m          | xy   | N    |           | OPT     | surface_roughness_for_heat
 CN_PRCP      | kg/m^2/s   | xy   | N    |           | OPT     | surface_conv._rain_flux_needed_by_land
 NCN_PRCP     | kg/m^2/s   | xy   | N    |           | OPT     | Non-convective precipitation
 AREA         | m^2        | xy   | N    |           | OPT     | agrid_cell_area
 AIRDENS      | kg/m^3     | xyz  | C    |           | OPT     | moist_air_density
 DELP         | Pa         | xyz  | C    |           | OPT     | pressure_thickness
 RH2          | 1          | xyz  | C    |           | OPT     | Rel_Hum_after_moist
 ZLE          | m          | xyz  | E    |           | OPT     | geopotential_height
 DU           | kg kg-1    | xyz  | C    | 5         | OPT     | Dust Mixing Ratio all bins
 SS           | kg kg-1    | xyz  | C    | 5         | OPT     | Sea Salt Mixing Ratio all bins
 SO4          | kg kg-1    | xyz  | C    |           | OPT     | Sulfate Mixing Ratio
```
YAML:
```yaml
component: DU
import_state_var: du01_importState # default importState
import_state:
 LWI:      {units: 1, dims: xy, vloc: N, restart: OPT, long_name: land-ocean_ice_mask}
 TROPP:    {units: Pa, dims: xy, vloc: N, restart: OPT, long_name: tropopause_pressure_based_on_blended_estimattion}
 USTAR:    {units: m s-1, dims: xy, vloc: N, restart: OPT, long_name: surface_velocity_scale}
 ZPBL:     {units: 1m, dims: xy, vloc: N, restart: OPT, long_name: planetary_boundary_layer_height}
 SH:       {units: w m-2, dims: xy, vloc: N, restart: OPT, long_name: sensible_heat_flux_from_turbulence}
 Z0H:      {units: m, dims: xy, vloc: N, restart: OPT, long_name: surface_roughness_for_heat}
 CN_PRCP:  {units: kg/m^2/s, dims: xy, vloc: N, restart: OPT, long_name: surface_conv._rain_flux_needed_by_land}
 NCN_PRCP: {units: kg/m^2/s, dims: xy, vloc: N, restart: OPT, long_name: Non-convective precipitation }
 AREA:     {units: m^2, dims: xy, vloc: N, restart: OPT, long_name: agrid_cell_area}
 AIRDENS:  {units: kg/m^3, dims: xyz, vloc: C, restart: OPT, long_name: moist_air_density}
 DELP:     {units: Pa, dims: xyz, vloc: C, restart: OPT, long_name: pressure_thickness}
 T:        {units: K, dims: xyz, vloc: C, restart: OPT, long_name: air_temperature}
 RH2:      {units: 1, dims: xyz, vloc: C, restart: OPT, long_name: Rel_Hum_after_moist}
 ZLE:      {units: m, dims: xyz, vloc: E, restart: OPT, long_name: geopotential_height}
 DU:       {units: kg kg-1, dims: xyz, vloc: C, ungridded: [5], restart: OPT, long_name: Dust Mixing Ratio all bins}
 SU:       {units: kg kg-1, dims: xyz, vloc: C, ungridded: [5], restart: OPT, long_name: Dust Mixing Ratio all bins}
 SO4:      {units: kg kg-1, dims: xyz, vloc: C, restart: OPT, long_name: Dust Mixing Ratio all bins}
```
Seems as easy to read, especially if we take account of the fact the editor will syntax highlight the yaml file to call out the keys etc... at least when they don't choose blue and black

This is where the exec like format runs out of steam
If we were to include a name and values for the ungridded dimensions ungridded dimensions the lines would get really long as you would have to add columns for the extra information for the ungridded dimension (just making up some value here), i.e. if there were 2, this would be really unwieldy, although I do recall was an idea about embedding yaml in this for hconfig parse?
```
component: Irrad
category: IMPORT
#----------------------------------------------------------------------------------------
#  VARIABLE                | DIMENSIONS  |          Additional Metadata
#----------------------------------------------------------------------------------------
     NAME     | UNITS      | DIMS | VLOC | UNGRIDDED  | UNGRIDDED_NAME   | UNGRIDDED_UNITS | UNGRIDDED_VALUES | RESTART | LONG NAME
#----------------------------------------------------------------------------------------
 DRBANDN  | 1                   | xy      |   N.     | 16                   |   Irrad_Bands  | nm           |   600 590 580 570 560 550 540 530 520 510 500 490 480 570 460 450      | OPT     |  normalized_surface_downwelling_shortwave_beam_flux_per_band

```
I do admit to avoid the long times we have to go back to block style which I agree is perhaps harder to scan, on the other hand you might not be able to read the whole line in the first place with the above especially if you try to get the columns to line up if you are on a small screen so the yaml becomes easier to read

```yaml
import_state:
  DRBAND:
      units: 1
      dims: xy
      vloc: N
      ungridded_dims: # The key name(s) become the ungridded dim name
          Irrad_bands:
             units: nm
             values: [600, 590, 580, 570, 560, 550, 540, 530, 520, 510, 500, 490, 480, 570, 460, 450]

  ```
Or you could mix block and flow style:
```yaml
import_state:
  LWI:      {units: 1, dims: xy, vloc: N, restart: OPT, long_name: land-ocean_ice_mask}
  DRBAND:
      units: 1
      dims: xy
      vloc: N
      ungridded_dims: # The key name(s) become the ungridded dim name
          Irrad_bands:
             units: nm
             values: [600, 590, 580, 570, 560, 550, 540, 530, 520, 510, 500, 490, 480, 570, 460, 450]
```

**Comment by mathomp4** [comment]
I suppose if you want "pretty", this is also valid (per `yamllint`):

```yaml
component: DU
import_state_var: du01_importState # default importState
import_state:
 LWI:      {units: 1,        dims: xy,  vloc: N, restart: OPT,   long_name: land-ocean_ice_mask}
 TROPP:    {units: Pa,       dims: xy,  vloc: N, restart: OPT,   long_name: tropopause_pressure_based_on_blended_estimattion}
 USTAR:    {units: m s-1,    dims: xy,  vloc: N, restart: OPT,   long_name: surface_velocity_scale}
 ZPBL:     {units: 1m,       dims: xy,  vloc: N, restart: OPT,   long_name: planetary_boundary_layer_height}
 SH:       {units: w m-2,    dims: xy,  vloc: N, restart: OPT,   long_name: sensible_heat_flux_from_turbulence}
 Z0H:      {units: m,        dims: xy,  vloc: N, restart: OPT,   long_name: surface_roughness_for_heat}
 CN_PRCP:  {units: kg/m^2/s, dims: xy,  vloc: N, restart: OPT,   long_name: surface_conv._rain_flux_needed_by_land}
 NCN_PRCP: {units: kg/m^2/s, dims: xy,  vloc: N, restart: OPT,   long_name: Non-convective precipitation }
 AREA:     {units: m^2,      dims: xy,  vloc: N, restart: OPT,   long_name: agrid_cell_area}
 AIRDENS:  {units: kg/m^3,   dims: xyz, vloc: C, restart: OPT,   long_name: moist_air_density}
 DELP:     {units: Pa,       dims: xyz, vloc: C, restart: OPT,   long_name: pressure_thickness}
 T:        {units: K,        dims: xyz, vloc: C, restart: OPT,   long_name: air_temperature}
 RH2:      {units: 1,        dims: xyz, vloc: C, restart: OPT,   long_name: Rel_Hum_after_moist}
 ZLE:      {units: m,        dims: xyz, vloc: E, restart: OPT,   long_name: geopotential_height}
 SO4:      {units: kg kg-1,  dims: xyz, vloc: C, restart: OPT,   long_name: Dust Mixing Ratio all bins}
 DU:       {units: kg kg-1,  dims: xyz, vloc: C, ungridded: [5], restart: OPT, long_name: Dust Mixing Ratio all bins}
 SU:       {units: kg kg-1,  dims: xyz, vloc: C, ungridded: [5], restart: OPT, long_name: Dust Mixing Ratio all bins}

```

**Comment by tclune** [comment]
@mathomp4 Thank you for the extra formatting..   I was about to do that.  (Some would have insisted on it ...)

Note - I think there are some columns, not shown in this case that make things worse (lots of empty space).   E.g., if some vars have ungridded dims and others do not then the columnar form will look much different.

I will try to get @amdasilva to consider ...

**Comment by tclune** [comment]
Ah - here is the complexity that the above example does not include.   Again ungridded dims is the main example but I think there are a few other cases.     YAML is sensitive to commas.  CSV is also, but Arlindo's convention is for pipe `|` as the separator and we disallow that character in all other uses.

Now, for some cases where we want a comma inside a value, we could simply use quotes to keep yaml out of it.   But even then to the eye it could be confusing.    I would want to support a nested stucure instead. As an example, consider the "dependencies" column in which one lists the short name of other exports that this export depends on:
```yaml
DU:  {units: ... , dependencies:  a1,a2,a3}
```
Technically that is not valid yaml.   We could fix by requiring "", which works well in this case (but not in ungridded dims):
```yaml
DU:  {units: ... , dependencies:  "a1,a2,a3"}
```
But ... those less fluent in yaml might be tripped by the obscure error.

Now for ungridded.   The natural expression in yaml is as a sequence of mappings.   The size of the sequence is the number of ungridded dimensions.     But this begs the question of how ACG will actually write the Fortran.  Consider this simple example:
```yaml
DU: {units: ..., dims: xyz,   ungridded: [{name: radius, units: nm, extent: nbin}]
```
The call to `MAPL_AddVariableSpec()` will have an argument `ungridded` but ... what do we use as the value?   We could just send the string `"[{name: radius, units: nm, extent: nbin}]"` and let Fortran deal with it.   Or we could have the ACG perform a series of constructors to make the Fortran equivalent:
```f90
call MAPL_AddVariableSpec(...,ungridded_dims=UngriddedDims([UngriddedDim(name='radius', units='nm', extent=nbin)]))
```
(Note the care that @darianboggs needs to put quotes around `radius` and `nm` and **not** around `nbin`. )

**Comment by mathomp4** [comment]
Hmm. I just tried adding:
```
DU: {units: ..., dependencies: a1,a2,a3}
```
in a test file and `yamllint` was actually valid, but as @tclune it doesn't do what we want. It looks like:
```
│                  │ │          │ ╭──────────────┬────────────────────────────╮                    │ │
│                  │ │ DU       │ │ units        │ kg kg-1                    │                    │ │
│                  │ │          │ │ dims         │ xyz                        │                    │ │
│                  │ │          │ │ vloc         │ C                          │                    │ │
│                  │ │          │ │ restart      │ OPT                        │                    │ │
│                  │ │          │ │ long_name    │ Dust Mixing Ratio all bins │                    │ │
│                  │ │          │ │              │ ╭───┬───╮                  │                    │ │
│                  │ │          │ │ ungridded    │ │ 0 │ 5 │                  │                    │ │
│                  │ │          │ │              │ ╰───┴───╯                  │                    │ │
│                  │ │          │ │ dependencies │ a1                         │                    │ │
│                  │ │          │ │ a2           │                            │                    │ │
│                  │ │          │ │ a3           │                            │                    │ │
│                  │ │          │ ╰──────────────┴────────────────────────────╯                    │ │
```
So, we have `a1` as a dependency, but then `a2` and `a3` are now new keys.

**Comment by mathomp4** [comment]
Ooh. But if we go block style, this:
```yaml
  DU:
    units: kg kg-1
    dims: xyz
    vloc: C
    restart: OPT
    long_name: Dust Mixing Ratio all bins
    ungridded: [5]
    dependencies: a1, a2, a3
```
might be okay:
```
│                  │ │          │ ╭──────────────┬────────────────────────────╮                    │ │
│                  │ │ DU       │ │ units        │ kg kg-1                    │                    │ │
│                  │ │          │ │ dims         │ xyz                        │                    │ │
│                  │ │          │ │ vloc         │ C                          │                    │ │
│                  │ │          │ │ restart      │ OPT                        │                    │ │
│                  │ │          │ │ long_name    │ Dust Mixing Ratio all bins │                    │ │
│                  │ │          │ │              │ ╭───┬───╮                  │                    │ │
│                  │ │          │ │ ungridded    │ │ 0 │ 5 │                  │                    │ │
│                  │ │          │ │              │ ╰───┴───╯                  │                    │ │
│                  │ │          │ │ dependencies │ a1, a2, a3                 │                    │ │
│                  │ │          │ ╰──────────────┴────────────────────────────╯                    │ │
```

**Comment by mathomp4** [comment]
Huh. I just noticed the weirdness with `ungridded`:
```
│                  │ │          │ │              │ ╭───┬───╮                  │                    │ │
│                  │ │          │ │ ungridded    │ │ 0 │ 5 │                  │                    │ │
│                  │ │          │ │              │ ╰───┴───╯                  │                    │ │
```

I wonder why that is happening?

**Comment by tclune** [comment]
I am surprised that the yaml above was legal.    I thought every entry in a mapping had to have  a `key: value` structure.  And `a1,a2,a3` definitely does not.

**Comment by darianboggs** [comment]
I appreciate @bena-nasa starting this discussion. I put aside my designs for adding a capability to use YAML for the specs file because it seemed fruitless. If we think this is "fruity", we could have a "live" discussion on Microsoft Teams.

For now, I'll say that the current tabular format is adequate for truly tabular information. The pipe delimitation allows the comma in row values without quoting.

The tabular format is poorly suited for structured data. If we choose not to support YAML for the current specs, we should not try to support structured specs. If users want structured specs, we can use YAML for anything new. If we choose to use YAML in part or in whole (with the tabular format still allowed for existing columns), Python is good for parsing the YAML. Fortran seems adequate for tabular data, but it doesn't seem suited for structured data.

ACG2 and ACG3 are both designed around structured data in the form of Python dict instances.
To make the current spec files usable, ACG2 and ACG3 convert each table in the spec file into a simple dict that corresponds to multiple YAML maps. Because ACG2 treats IMPORT, EXPORT, and INTERNAL separately, the converted data is a Python dict of dict instances where the key is the state. In ACG3, the dict is flattened since each spec has a column for state variable and a column for state intent.

**Comment by tclune** [comment]
Spoke to Arlindo in the hallway about the "revolt".    A compromise suggestion is to put the columns (keys) in a sequence above the table and use sequences (lists) for the rows.

Then we still have yaml, but don't need to repeat the keys in every row.  Visually this should be about as good as the CSV form.  But ... we still need to deal with the commas inside of values as YAML insists on commas (unlike comma-separated-values - ironic).

**Comment by darianboggs** [comment]
Yes. That's one of my designs. There are a number of different paths.

**Comment by amdasilva** [comment]
@bena-nasa @tclune Sorry, I am coming late to this.  I get that we should strive to unify around yaml as the format for rc files. Perhaps I am a bit dyslexic, but this is not very human  readable:

```yaml
component: DU
import_state_var: du01_importState # default importState
import_state:
 LWI:      {units: 1, dims: xy, vloc: N, restart: OPT, long_name: land-ocean_ice_mask}
 TROPP:    {units: Pa, dims: xy, vloc: N, restart: OPT, long_name: tropopause_pressure_based_on_blended_estimattion}
 USTAR:    {units: m s-1, dims: xy, vloc: N, restart: OPT, long_name: surface_velocity_scale}
 ZPBL:     {units: 1m, dims: xy, vloc: N, restart: OPT, long_name: planetary_boundary_layer_height}
 SH:       {units: w m-2, dims: xy, vloc: N, restart: OPT, long_name: sensible_heat_flux_from_turbulence}
 Z0H:      {units: m, dims: xy, vloc: N, restart: OPT, long_name: surface_roughness_for_heat}
 CN_PRCP:  {units: kg/m^2/s, dims: xy, vloc: N, restart: OPT, long_name: surface_conv._rain_flux_needed_by_land}
 NCN_PRCP: {units: kg/m^2/s, dims: xy, vloc: N, restart: OPT, long_name: Non-convective precipitation }
 AREA:     {units: m^2, dims: xy, vloc: N, restart: OPT, long_name: agrid_cell_area}
 AIRDENS:  {units: kg/m^3, dims: xyz, vloc: C, restart: OPT, long_name: moist_air_density}
 DELP:     {units: Pa, dims: xyz, vloc: C, restart: OPT, long_name: pressure_thickness}
 T:        {units: K, dims: xyz, vloc: C, restart: OPT, long_name: air_temperature}
 RH2:      {units: 1, dims: xyz, vloc: C, restart: OPT, long_name: Rel_Hum_after_moist}
 ZLE:      {units: m, dims: xyz, vloc: E, restart: OPT, long_name: geopotential_height}
 DU:       {units: kg kg-1, dims: xyz, vloc: C, ungridded: [5], restart: OPT, long_name: Dust Mixing Ratio all bins}
 SU:       {units: kg kg-1, dims: xyz, vloc: C, ungridded: [5], restart: OPT, long_name: Dust Mixing Ratio all bins}
 SO4:      {units: kg kg-1, dims: xyz, vloc: C, restart: OPT, long_name: Dust Mixing Ratio all bins}
```

What about of we replace the inner dictionaries with positional strings:
```yaml
component: DU
import_state_var: du01_importState # default importState
#---------------|------------|------|------|-----------|---------|------------------------------------------------
 __HEADER__:   '| UNITS      | DIMS | VLOC | UNGRIDDED | RESTART | LONG NAME'
#---------------|------------|------|------|-----------|---------|------------------------------------------------
 LWI:          '| 1          | xy   | N    |           | OPT     | land-ocean-ice_mask'
 TROPP:        '| Pa         | xy   | N    |           | OPT     | tropopause_pressure_based_on_blended_estimate'
 USTAR :       '| m s-1      | xy   | N    |           | OPT     | surface_velocity_scale'
 ZPBL:         '| m          | xy   | N    |           | OPT     | planetary_boundary_layer_height'
 SH:           '| w m-2      | xy   | N    |           | OPT     | sensible_heat_flux_from_turbulence'
 Z0H:          '| m          | xy   | N    |           | OPT     | surface_roughness_for_heat'
 CN_PRCP:      '| kg/m^2/s   | xy   | N    |           | OPT     | surface_conv._rain_flux_needed_by_land'
 NCN_PRCP:     '| kg/m^2/s   | xy   | N    |           | OPT     | Non-convective precipitation'
 AREA:         '| m^2        | xy   | N    |           | OPT     | agrid_cell_area'
 AIRDENS:      '| kg/m^3     | xyz  | C    |           | OPT     | moist_air_density'
 DELP:         '| Pa         | xyz  | C    |           | OPT     | pressure_thickness'
 RH2:          '| 1          | xyz  | C    |           | OPT     | Rel_Hum_after_moist'
 ZLE :         '| m          | xyz  | E    |           | OPT     | geopotential_height'
 DU:           '| kg kg-1    | xyz  | C    | 5         | OPT     | Dust Mixing Ratio all bins'
 SS:           '| kg kg-1    | xyz  | C    | 5         | OPT     | Sea Salt Mixing Ratio all bins'
 SO4 :         '| kg kg-1    | xyz  | C    |           | OPT     | Sulfate Mixing Ratio'
#---------------|------------|------|------|-----------|---------|------------------------------------------------
```
The ACG can easily turn these |-delimited strings into your dictionaries and yet preserve readability. What about this for a compromise?
