### ISSUE TITLE
Problem freeing resources in pflogger

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#514]
From @gmao-esherman :  "Sometime mid last week I was getting intel compiler errors at the end of my runs. The GEOSgcm Run Status is 0, the model variable values look good, checkpoint/restarts and model output are still being written. The intel compiler stack trace in the slurm log is unintelligible to me. Ben provided much help setting up and using arm forge and ddt to get an intelligible stack trace (image attached). It seems like plfogger is having trouble freeing up shared memory at the very end of the run. If I comment out all mentions of pflogger the error goes away. Ben was also able to recreate the error using plflogger. We thought we should let you know."
![Screen Shot 2020-07-31 at 4 36 47 PM](https://user-images.githubusercontent.com/6225888/89191458-f57ec200-d570-11ea-80ef-bf602a4bd125.png)

**Comment by tclune** [comment]
This seems a bit similar to an issue that @weiyuan-jiang fixed a while back.   I'm wondering if that fix is not yet in the baselibs that you are using.  (Which is why I'm referencing @mathomp4 )

@gmao-esherman please let us know which baselibs you are using.

**Comment by gmao-esherman** [comment]
According to @env/g5modules I am using /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.13-SLES12/x86_64-unknown-linux-gnu/ifort_18.0.5.274-intelmpi_19.1.0.166

This was tested on NCCS discover using SLES12.

**Comment by bena-nasa** [comment]
I have reproduced this as well using the logging.yaml file Elliot provided with 6.0.13 baselibs and the head of MAPL develop :
```
schema_version: 1

locks:
   mpi:
      class: MpiLock
      comm:  MPI_COMM_WORLD

formatters:
   basic:
      class: Formatter
      format:  '%(name)a~: %(level_name)a~: %(message)a'
   mpi:
      class: MpiFormatter
      format:  '%(mpi_rank)i4.4~: %(name)~: %(level_name)a~: %(message)a'
      comm: MPI_COMM_WORLD
   column:
      class: Formatter
      format: '(%(i)i3.3,%(j)i3.3): %(level_name)'

handlers:
   console:
      class: streamhandler
      formatter: basic
      unit: OUTPUT_UNIT
      level: WARNING


   warnings:
      class:  FileHandler
      filename: warnings_and_errors.log
      lock: mpi
      level: WARNING
      formatter: basic

   errors:
      class:  StreamHandler
      formatter: basic
      unit: ERROR_UNIT
      level: ERROR

   mpi_shared:
      class: FileHandler
      filename: allPEs.log
      formatter: mpi
      comm: MPI_COMM_WORLD
      lock: mpi
      rank_keyword: rank
      level: DEBUG

   volcanic_emissions:
      class: FileHandler
      formatter: mpi
      filename: volcanic_emissions
      lock: mpi
      comm: MPI_COMM_WORLD
      rank_prefix: rank
      level: DEBUG

   mpi_debug:
      class: MpiFileHandler
      formatter: basic
      filename:  debug_%(rank)i3.3~.log
      comm: MPI_COMM_WORLD
      rank_prefix: rank
      level: DEBUG

root:
   parallel: true
   handlers: [warnings,errors]
   level: WARNING
loggers:

   volcanic_emissions:
       parallel: true
       handlers: [volcanic_emissions]
       lock: mpi
       propagate: false
       level: DEBUG


   parallel:
      parallel: true
      handlers: [mpi_debug,mpi_shared]
      lock: mpi
      propagate: false
      level: DEBUG

   CAP.GCM.AGCM.PHYSICS:
       parallel: true
       handlers: [mpi_shared]
       lock: mpi
       level: WARNING
       root_level: INFO

   MAPL:
       parallel: true
       handlers: [mpi_shared]
       lock: mpi
#       propagate: false
       level: INFO
       root_level: DEBUG


   errors:
       handlers: [errors]
       parallel: true
       lock: mpi
       level: ERROR
```
The trash reports a
[borgt138:1799 :0:1799] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1c0)
It it like the winfree is trying to free something that was already freed.
I find that if I comment out the CAP.GCM.AGCM.PHYSICS and MAPL loggers the crash dissapears.
